import = [
    "~/.config/alacritty/themes/theme.toml"
]

[font]
normal = { family = "Azeret Mono", style = "Regular" }
size = 9

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 600
unfocused_hollow = true

[window.padding]
x = 5
y = 5
