general.import = [
    "~/.config/alacritty/themes/theme.toml"
]

[font]
normal = { family = "JetBrainsMono", style = "Bold" }
bold = { style = "Bold" }
italic = { style = "Bold Italic" }
bold_italic = { style = "Bold Italic" }
size = 13

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_interval = 500 
unfocused_hollow = false 

[window.padding]
x = 5
y = 5
