#!/usr/bin/env sh
mode="$1"

case $mode in
    "region")
        grim -g "$(slurp)" - | swappy -f -
        ;;
    "window")
        geometry=$(hyprctl activewindow -j | jq -r '.at.x, -at.y, .size.x, .size.y' | tr '\n' ' ')
        read -r x y width height <<EOF
$geometry
EOF
        grim -g "${x},${y} ${width}x${height}" - | swappy -f -
        ;;
    "output")
        output=$(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name')
        grim -o "$output" - | swappy -f -
        ;;
    "all")
        grim - | swappy -f -
        ;;
    *)
        echo >&2 "unsupported command \"$mode\""
        echo >&2 "Usage:"
        echo >&2 "screenshot.sh <region|window|output|all>"
        exit 1
esac
