vim.api.nvim_set_hl(0, "Normal", { bg = "none" })
vim.cmd("hi StatusLine guibg=#1E1F22 guifg=none")
vim.cmd("hi! LineNr guibg=none guifg=#444444")
vim.cmd("hi MsgArea guibg=none guifg=none")
vim.api.nvim_set_hl(0, "Normal", { bg = "NONE" })
vim.api.nvim_set_hl(0, "NormalNC", { bg = "NONE" })

-- diagnostics
vim.api.nvim_set_hl(0, "SLDiagError", { fg = "#ff3131", bold = true })
vim.api.nvim_set_hl(0, "SLDiagWarn", { fg = "#ffd700", bold = true })
vim.api.nvim_set_hl(0, "SLDiagHint", { fg = "#00ffff", bold = true })
vim.api.nvim_set_hl(0, "SLDiagInfo", { fg = "#89cff0", bold = true })

-- diagnostics
vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#5c0a5c", bg = "none" })
vim.api.nvim_set_hl(0, "DiagnosticSignError", { fg = "#ff3131", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticSignWarn", { fg = "#ffd700", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticSignHint", { fg = "#00ffff", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticSignInfo", { fg = "#89cff0", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticFloatingError", { fg = "#f44747", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticFloatingWarn", { fg = "#ffd700", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticFloatingHint", { fg = "#00ffff", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticFloatingInfo", { fg = "#89cff0", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#ff3131", bg = "none" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#ffd700", bg = "none" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#00ffff", bg = "none" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#89cff0", bg = "none" })

-- tab
vim.api.nvim_set_hl(0, "TabLine", { fg = "#6c6c6c", bg = "none", italic = true })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#d7af87", bg = "none", bold = true })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "none" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = "none" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "none" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#d7af87", bg = "#303030", bold = true })
